# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Startseite
    url: /#top
    weight: 10
  - name: Erste Schritte
    weight: 20
    hasChildren: true
  - parent: Erste Schritte
    name: Bin ich Mediensüchtig?
    url: erste_schritte/bin-ich-mediensuechtig/
  - name: Meetings
    url: /#solutions
    weight: 30
  - name: Resourcen
    weight: 40
    hasChildren: true
  - parent: Resourcen
    name: Literatur
    url: blog/
